# Generated by Django 5.0.6 on 2024-07-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_contactmessage_replied_contactmessage_reply_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='reply_message',
            new_name='admin_reply',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='replied',
        ),
    ]
