# Generated by Django 5.0.6 on 2024-07-28 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_rename_reply_message_contactmessage_admin_reply_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactMessage',
        ),
    ]
