# Generated by Django 5.0.6 on 2024-07-31 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_fileupload'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
