# Generated by Django 5.0.6 on 2024-08-01 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_feedback_unique_together_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegePoster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='posters/')),
            ],
        ),
    ]
